#!/usr/bin/env python
import os
import re
import sys

from subprocess import *

DISABLE_MSGS = " ".join("--disable-msg=%s" % msg
                        for msg in [
        "W0401", #wildcard imports
        ])

filename = sys.argv[1]

pathname = os.path.dirname(os.path.abspath(filename))
while pathname and os.path.exists(os.path.join(pathname, "__init__.py")):
    pathname = os.path.dirname(pathname)

popen = Popen("PYTHONPATH=%s pylint -f parseable -r n --disable-msg-cat=C,R %s %s" %
          (pathname, DISABLE_MSGS, sys.argv[1]), shell = True, stdout = PIPE)
p = popen.stdout
data = p.read()

for line in data.splitlines():
    match = re.search("\\[([WE])(, (.+?))?\\]", line)
    if match:
        kind = match.group(1)
        func = match.group(3)

        if kind == "W":
            msg = "Warning"
        else:
            msg = "Error"

        if func:
            line = re.sub("\\[([WE])(, (.+?))?\\]",
                          "%s (%s):" % (msg, func), line)
        else:
            line = re.sub("\\[([WE])?\\]", "%s:" % msg, line)
        print line

    p.close()
